version: 2.1 
jobs: 
  build:
    working_directory: ~/app
    docker: 
      - image: circleci/node:10.16.3
    steps: 
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache: 
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: npm-install
          command: npm install
      - save_cache: 
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: 
          name: test
          command: ./node_modules/.bin/nyc npm t --reporter=html
      - run:
          name: code-coverage
          command: './node_modules/.bin/nyc report --reporter=html'
      - store_artifacts: 
          path: .nyc_output
          prefix: tests
      - store_artifacts: 
          path: coverage
          prefix: coverage
      - store_test_results: 
          path: .nyc_output
